version: '3.8'

services:
  rabbitmq:
    build:
      context: .
      dockerfile: infra/rabbitmq/Dockerfile
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
      - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
    env_file:
      - infra/.env
    healthcheck:
      test: [ "CMD", "nc", "-z", "localhost", "5672" ]
      interval: 5s
      timeout: 15s
      retries: 1

  postgres:
    container_name: postgres_notifications
    image: postgres:13.0-alpine
    restart: always
    expose:
      - "5432"
    env_file:
      - infra/.env
    volumes:
      - postgres_notification_data:/var/lib/postgresql/data

  admin_api:
    container_name: notification_admin
    build:
      context: .
      dockerfile: infra/admin/Dockerfile
    env_file:
      - infra/.env
    volumes:
      - nginx_static:/app/static
      - nginx_media:/app/media

  user_api:
    container_name: user_service
    build:
      context: .
      dockerfile: infra/users/Dockerfile
    ports:
      - "8002:8002"

  api:
    container_name: notification_api
    build:
      context: .
      dockerfile: infra/api/Dockerfile
    ports:
      - "8001:8000"

  worker:
    container_name: worker
    build:
      context: .
      dockerfile: infra/worker/Dockerfile
    restart:
      always
    env_file:
      - infra/.env
    depends_on:
      - user_api
      - postgres

  scheduler:
    container_name: scheduler
    build:
      context: .
      dockerfile: infra/scheduler/Dockerfile
    restart:
      always
    env_file:
      - infra/.env
    depends_on:
      - user_api
      - postgres
      - api

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "8000:80"
    volumes:
      - ./infra/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./infra/nginx/conf.d:/etc/nginx/conf.d
      - nginx_static:/usr/share/nginx/www/static
      - nginx_media:/usr/share/nginx/www/media

volumes:
  postgres_notification_data:
  nginx_static:
  nginx_media:
